/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedCompilationsRouteImport } from './routes/_authenticated/compilations'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedIdentitiesRouteImport } from './routes/_authenticated/identities'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as OrderTokenRouteImport } from './routes/order.$token'
import { Route as StoreHandleRouteImport } from './routes/store.$handle'
import { Route as AuthenticatedCatalogIndexRouteImport } from './routes/_authenticated/catalog.index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as ApiPublicMetaOauthCallbackRouteImport } from './routes/api/public/meta/oauth-callback'
import { Route as ApiPublicPaypalIpnRouteImport } from './routes/api/public/paypal/ipn'
import { Route as ApiPublicSoundcloudOauthCallbackRouteImport } from './routes/api/public/soundcloud/oauth-callback'
import { Route as ApiPublicStorePreviewRouteImport } from './routes/api/public/store/preview'
import { Route as ApiPublicStripeStoreIdRouteImport } from './routes/api/public/stripe/$storeId'
import { Route as ApiPublicTiktokOauthCallbackRouteImport } from './routes/api/public/tiktok/oauth-callback'
import { Route as ApiPublicYoutubeOauthCallbackRouteImport } from './routes/api/public/youtube/oauth-callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompilationsRoute =
  AuthenticatedCompilationsRouteImport.update({
    id: '/compilations',
    path: '/compilations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIdentitiesRoute = AuthenticatedIdentitiesRouteImport.update({
  id: '/identities',
  path: '/identities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OrderTokenRoute = OrderTokenRouteImport.update({
  id: '/order/$token',
  path: '/order/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreHandleRoute = StoreHandleRouteImport.update({
  id: '/store/$handle',
  path: '/store/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCatalogIndexRoute =
  AuthenticatedCatalogIndexRouteImport.update({
    id: '/catalog/',
    path: '/catalog/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMetaOauthCallbackRoute =
  ApiPublicMetaOauthCallbackRouteImport.update({
    id: '/api/public/meta/oauth-callback',
    path: '/api/public/meta/oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaypalIpnRoute = ApiPublicPaypalIpnRouteImport.update({
  id: '/api/public/paypal/ipn',
  path: '/api/public/paypal/ipn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSoundcloudOauthCallbackRoute =
  ApiPublicSoundcloudOauthCallbackRouteImport.update({
    id: '/api/public/soundcloud/oauth-callback',
    path: '/api/public/soundcloud/oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStorePreviewRoute = ApiPublicStorePreviewRouteImport.update({
  id: '/api/public/store/preview',
  path: '/api/public/store/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeStoreIdRoute = ApiPublicStripeStoreIdRouteImport.update({
  id: '/api/public/stripe/$storeId',
  path: '/api/public/stripe/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTiktokOauthCallbackRoute =
  ApiPublicTiktokOauthCallbackRouteImport.update({
    id: '/api/public/tiktok/oauth-callback',
    path: '/api/public/tiktok/oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicYoutubeOauthCallbackRoute =
  ApiPublicYoutubeOauthCallbackRouteImport.update({
    id: '/api/public/youtube/oauth-callback',
    path: '/api/public/youtube/oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/compilations': typeof AuthenticatedCompilationsRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/identities': typeof AuthenticatedIdentitiesRoute
  '/store': typeof AuthenticatedStoreRoute
  '/order/$token': typeof OrderTokenRoute
  '/store/$handle': typeof StoreHandleRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/catalog/': typeof AuthenticatedCatalogIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/meta/oauth-callback': typeof ApiPublicMetaOauthCallbackRoute
  '/api/public/paypal/ipn': typeof ApiPublicPaypalIpnRoute
  '/api/public/soundcloud/oauth-callback': typeof ApiPublicSoundcloudOauthCallbackRoute
  '/api/public/store/preview': typeof ApiPublicStorePreviewRoute
  '/api/public/stripe/$storeId': typeof ApiPublicStripeStoreIdRoute
  '/api/public/tiktok/oauth-callback': typeof ApiPublicTiktokOauthCallbackRoute
  '/api/public/youtube/oauth-callback': typeof ApiPublicYoutubeOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/compilations': typeof AuthenticatedCompilationsRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/identities': typeof AuthenticatedIdentitiesRoute
  '/store': typeof AuthenticatedStoreRoute
  '/order/$token': typeof OrderTokenRoute
  '/store/$handle': typeof StoreHandleRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/catalog': typeof AuthenticatedCatalogIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/api/public/meta/oauth-callback': typeof ApiPublicMetaOauthCallbackRoute
  '/api/public/paypal/ipn': typeof ApiPublicPaypalIpnRoute
  '/api/public/soundcloud/oauth-callback': typeof ApiPublicSoundcloudOauthCallbackRoute
  '/api/public/store/preview': typeof ApiPublicStorePreviewRoute
  '/api/public/stripe/$storeId': typeof ApiPublicStripeStoreIdRoute
  '/api/public/tiktok/oauth-callback': typeof ApiPublicTiktokOauthCallbackRoute
  '/api/public/youtube/oauth-callback': typeof ApiPublicYoutubeOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/compilations': typeof AuthenticatedCompilationsRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRoute
  '/_authenticated/identities': typeof AuthenticatedIdentitiesRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/order/$token': typeof OrderTokenRoute
  '/store/$handle': typeof StoreHandleRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/catalog/': typeof AuthenticatedCatalogIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/meta/oauth-callback': typeof ApiPublicMetaOauthCallbackRoute
  '/api/public/paypal/ipn': typeof ApiPublicPaypalIpnRoute
  '/api/public/soundcloud/oauth-callback': typeof ApiPublicSoundcloudOauthCallbackRoute
  '/api/public/store/preview': typeof ApiPublicStorePreviewRoute
  '/api/public/stripe/$storeId': typeof ApiPublicStripeStoreIdRoute
  '/api/public/tiktok/oauth-callback': typeof ApiPublicTiktokOauthCallbackRoute
  '/api/public/youtube/oauth-callback': typeof ApiPublicYoutubeOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/setup'
    | '/terms'
    | '/compilations'
    | '/connections'
    | '/identities'
    | '/store'
    | '/order/$token'
    | '/store/$handle'
    | '/projects/$id'
    | '/catalog/'
    | '/projects/'
    | '/api/public/meta/oauth-callback'
    | '/api/public/paypal/ipn'
    | '/api/public/soundcloud/oauth-callback'
    | '/api/public/store/preview'
    | '/api/public/stripe/$storeId'
    | '/api/public/tiktok/oauth-callback'
    | '/api/public/youtube/oauth-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/setup'
    | '/terms'
    | '/compilations'
    | '/connections'
    | '/identities'
    | '/store'
    | '/order/$token'
    | '/store/$handle'
    | '/projects/$id'
    | '/catalog'
    | '/projects'
    | '/api/public/meta/oauth-callback'
    | '/api/public/paypal/ipn'
    | '/api/public/soundcloud/oauth-callback'
    | '/api/public/store/preview'
    | '/api/public/stripe/$storeId'
    | '/api/public/tiktok/oauth-callback'
    | '/api/public/youtube/oauth-callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/setup'
    | '/terms'
    | '/_authenticated/compilations'
    | '/_authenticated/connections'
    | '/_authenticated/identities'
    | '/_authenticated/store'
    | '/order/$token'
    | '/store/$handle'
    | '/_authenticated/projects/$id'
    | '/_authenticated/catalog/'
    | '/_authenticated/projects/'
    | '/api/public/meta/oauth-callback'
    | '/api/public/paypal/ipn'
    | '/api/public/soundcloud/oauth-callback'
    | '/api/public/store/preview'
    | '/api/public/stripe/$storeId'
    | '/api/public/tiktok/oauth-callback'
    | '/api/public/youtube/oauth-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  SetupRoute: typeof SetupRoute
  TermsRoute: typeof TermsRoute
  OrderTokenRoute: typeof OrderTokenRoute
  StoreHandleRoute: typeof StoreHandleRoute
  ApiPublicMetaOauthCallbackRoute: typeof ApiPublicMetaOauthCallbackRoute
  ApiPublicPaypalIpnRoute: typeof ApiPublicPaypalIpnRoute
  ApiPublicSoundcloudOauthCallbackRoute: typeof ApiPublicSoundcloudOauthCallbackRoute
  ApiPublicStorePreviewRoute: typeof ApiPublicStorePreviewRoute
  ApiPublicStripeStoreIdRoute: typeof ApiPublicStripeStoreIdRoute
  ApiPublicTiktokOauthCallbackRoute: typeof ApiPublicTiktokOauthCallbackRoute
  ApiPublicYoutubeOauthCallbackRoute: typeof ApiPublicYoutubeOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/compilations': {
      id: '/_authenticated/compilations'
      path: '/compilations'
      fullPath: '/compilations'
      preLoaderRoute: typeof AuthenticatedCompilationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/identities': {
      id: '/_authenticated/identities'
      path: '/identities'
      fullPath: '/identities'
      preLoaderRoute: typeof AuthenticatedIdentitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/order/$token': {
      id: '/order/$token'
      path: '/order/$token'
      fullPath: '/order/$token'
      preLoaderRoute: typeof OrderTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$handle': {
      id: '/store/$handle'
      path: '/store/$handle'
      fullPath: '/store/$handle'
      preLoaderRoute: typeof StoreHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/catalog/': {
      id: '/_authenticated/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof AuthenticatedCatalogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/meta/oauth-callback': {
      id: '/api/public/meta/oauth-callback'
      path: '/api/public/meta/oauth-callback'
      fullPath: '/api/public/meta/oauth-callback'
      preLoaderRoute: typeof ApiPublicMetaOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal/ipn': {
      id: '/api/public/paypal/ipn'
      path: '/api/public/paypal/ipn'
      fullPath: '/api/public/paypal/ipn'
      preLoaderRoute: typeof ApiPublicPaypalIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/soundcloud/oauth-callback': {
      id: '/api/public/soundcloud/oauth-callback'
      path: '/api/public/soundcloud/oauth-callback'
      fullPath: '/api/public/soundcloud/oauth-callback'
      preLoaderRoute: typeof ApiPublicSoundcloudOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/store/preview': {
      id: '/api/public/store/preview'
      path: '/api/public/store/preview'
      fullPath: '/api/public/store/preview'
      preLoaderRoute: typeof ApiPublicStorePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/$storeId': {
      id: '/api/public/stripe/$storeId'
      path: '/api/public/stripe/$storeId'
      fullPath: '/api/public/stripe/$storeId'
      preLoaderRoute: typeof ApiPublicStripeStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tiktok/oauth-callback': {
      id: '/api/public/tiktok/oauth-callback'
      path: '/api/public/tiktok/oauth-callback'
      fullPath: '/api/public/tiktok/oauth-callback'
      preLoaderRoute: typeof ApiPublicTiktokOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/youtube/oauth-callback': {
      id: '/api/public/youtube/oauth-callback'
      path: '/api/public/youtube/oauth-callback'
      fullPath: '/api/public/youtube/oauth-callback'
      preLoaderRoute: typeof ApiPublicYoutubeOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCompilationsRoute: typeof AuthenticatedCompilationsRoute
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRoute
  AuthenticatedIdentitiesRoute: typeof AuthenticatedIdentitiesRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedCatalogIndexRoute: typeof AuthenticatedCatalogIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCompilationsRoute: AuthenticatedCompilationsRoute,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRoute,
  AuthenticatedIdentitiesRoute: AuthenticatedIdentitiesRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedCatalogIndexRoute: AuthenticatedCatalogIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  SetupRoute: SetupRoute,
  TermsRoute: TermsRoute,
  OrderTokenRoute: OrderTokenRoute,
  StoreHandleRoute: StoreHandleRoute,
  ApiPublicMetaOauthCallbackRoute: ApiPublicMetaOauthCallbackRoute,
  ApiPublicPaypalIpnRoute: ApiPublicPaypalIpnRoute,
  ApiPublicSoundcloudOauthCallbackRoute: ApiPublicSoundcloudOauthCallbackRoute,
  ApiPublicStorePreviewRoute: ApiPublicStorePreviewRoute,
  ApiPublicStripeStoreIdRoute: ApiPublicStripeStoreIdRoute,
  ApiPublicTiktokOauthCallbackRoute: ApiPublicTiktokOauthCallbackRoute,
  ApiPublicYoutubeOauthCallbackRoute: ApiPublicYoutubeOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
